export const colors = {
  red: 'red',
  blue: '#43b1e7',
  grey: 'grey',
  lightgrey: 'lightgrey',
  black: 'black',
  white: '#ffffff',
  whitesecondary: '#ebecef',
  // whitesecondary: '#f1f2f6',
  lightgreen: '#70dc95',
  green: '#39ca6c',
  lightblue: '#87bba2',
  greenblue: '#68b0ab',
  darkgrey: '#98999d',
};
